package com.prototypes.scenarios.service;

import com.prototypes.scenarios.dto.ImpactRunPayload;
import com.prototypes.scenarios.dto.PostEventRequestDto;
import com.prototypes.scenarios.entity.Scenario;
import com.prototypes.scenarios.entity.ScenarioImpactReport;
import com.prototypes.scenarios.repository.ImpactRunRepository;
import com.prototypes.scenarios.repository.ScenarioImpactReportRepository;
import com.prototypes.scenarios.repository.ScenarioRepository;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Integration tests verifying that ScenarioDetailService correctly triggers
 * impact report generation when handling IMPACT_COMPLETED and
 * IMPACT_DATA_REFRESHED events.
 *
 * <p>Uses the full Spring context with H2 in PostgreSQL compatibility mode
 * so that all Liquibase changesets and seed data are available.</p>
 *
 * <p>Seed data used:
 * <ul>
 *   <li>Scenario 1: a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d (MARKET_DATA, "FX Curve Recalibration", IMPACT_AVAILABLE)</li>
 *   <li>Report definition: aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaa002 (MARKET_DATA, "market_risk_summary", active)</li>
 * </ul>
 * </p>
 */
@SpringBootTest
@ActiveProfiles("integration")
@Transactional
class ImpactReportGenerationIntegrationTest {

    @Autowired
    private ScenarioDetailService scenarioDetailService;

    @Autowired
    private ScenarioImpactReportRepository scenarioImpactReportRepository;

    @Autowired
    private ScenarioRepository scenarioRepository;

    @Autowired
    private ImpactRunRepository impactRunRepository;

    // Scenario 1: FX Curve Recalibration -- MARKET_DATA type, seeded as IMPACT_AVAILABLE
    private static final UUID MARKET_DATA_SCENARIO_ID =
            UUID.fromString("a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d");

    // ========================================================================
    // Test 1: handleImpactCompleted triggers report generation
    // ========================================================================

    @Test
    void handleImpactCompleted_triggersReportGeneration() {
        // Arrange: Set scenario to IMPACT_PENDING so IMPACT_COMPLETED is allowed
        Scenario scenario = scenarioRepository.findByIdWithSummary(MARKET_DATA_SCENARIO_ID)
                .orElseThrow();
        scenario.getSummary().setWorkflowState("IMPACT_PENDING");
        scenarioRepository.save(scenario);

        // Count existing reports before the event
        long reportCountBefore = scenarioImpactReportRepository
                .findAllByScenarioId(MARKET_DATA_SCENARIO_ID).stream()
                .filter(r -> !"bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbb011".equals(r.getId().toString()))
                .count();

        // Act: Process IMPACT_COMPLETED event
        ImpactRunPayload impactRun = new ImpactRunPayload("2026-03-10T12:00:00", "COMPLETED");
        PostEventRequestDto request = new PostEventRequestDto(
                "IMPACT_COMPLETED", null, impactRun, null);
        scenarioDetailService.processEvent(MARKET_DATA_SCENARIO_ID, request, "System", "system");

        // Assert: Reports were generated for the scenario
        List<ScenarioImpactReport> allReports =
                scenarioImpactReportRepository.findAllByScenarioId(MARKET_DATA_SCENARIO_ID);

        // Filter out seed data reports (from changeset 033) by checking for new reports
        List<ScenarioImpactReport> newReports = allReports.stream()
                .filter(r -> !"bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbb011".equals(r.getId().toString()))
                .toList();

        // There is 1 active MARKET_DATA report definition, so at least 1 new report should exist
        assertFalse(newReports.isEmpty(),
                "At least one report should have been generated by handleImpactCompleted");

        // Verify at least one report has GENERATED status with market_risk_summary key
        boolean hasGeneratedReport = newReports.stream()
                .anyMatch(r -> "GENERATED".equals(r.getStatus())
                        && "market_risk_summary".equals(r.getReportKey()));
        assertTrue(hasGeneratedReport,
                "Should have a GENERATED report with key 'market_risk_summary'");
    }

    // ========================================================================
    // Test 2: Scenario workflow state transitions correctly even when
    //         report generation occurs
    // ========================================================================

    @Test
    void handleImpactCompleted_workflowStateTransitionsCorrectly() {
        // Arrange: Set scenario to DRAFT so IMPACT_COMPLETED is allowed
        Scenario scenario = scenarioRepository.findByIdWithSummary(MARKET_DATA_SCENARIO_ID)
                .orElseThrow();
        scenario.getSummary().setWorkflowState("DRAFT");
        scenarioRepository.save(scenario);

        // Act: Process IMPACT_COMPLETED event
        ImpactRunPayload impactRun = new ImpactRunPayload("2026-03-10T12:00:00", "COMPLETED");
        PostEventRequestDto request = new PostEventRequestDto(
                "IMPACT_COMPLETED", null, impactRun, null);
        scenarioDetailService.processEvent(MARKET_DATA_SCENARIO_ID, request, "System", "system");

        // Assert: Workflow state was updated to IMPACT_AVAILABLE
        Scenario updatedScenario = scenarioRepository.findByIdWithSummary(MARKET_DATA_SCENARIO_ID)
                .orElseThrow();
        assertEquals("IMPACT_AVAILABLE", updatedScenario.getSummary().getWorkflowState(),
                "Workflow state should be IMPACT_AVAILABLE after IMPACT_COMPLETED event");
    }

    // ========================================================================
    // Test 3: handleImpactDataRefreshed also triggers report generation
    // ========================================================================

    @Test
    void handleImpactDataRefreshed_triggersReportGeneration() {
        // Arrange: Scenario 1 is already in IMPACT_AVAILABLE, which allows IMPACT_DATA_REFRESHED
        // Count existing reports before the event
        List<ScenarioImpactReport> reportsBefore =
                scenarioImpactReportRepository.findAllByScenarioId(MARKET_DATA_SCENARIO_ID);
        int countBefore = reportsBefore.size();

        // Act: Process IMPACT_DATA_REFRESHED event
        ImpactRunPayload impactRun = new ImpactRunPayload("2026-03-10T13:00:00", "COMPLETED");
        PostEventRequestDto request = new PostEventRequestDto(
                "IMPACT_DATA_REFRESHED", null, impactRun, null);
        scenarioDetailService.processEvent(MARKET_DATA_SCENARIO_ID, request, "System", "system");

        // Assert: New reports were generated
        List<ScenarioImpactReport> reportsAfter =
                scenarioImpactReportRepository.findAllByScenarioId(MARKET_DATA_SCENARIO_ID);
        assertTrue(reportsAfter.size() > countBefore,
                "New reports should have been generated by handleImpactDataRefreshed. " +
                "Before: " + countBefore + ", After: " + reportsAfter.size());

        // Verify the workflow state is still IMPACT_AVAILABLE after data refresh
        Scenario updatedScenario = scenarioRepository.findByIdWithSummary(MARKET_DATA_SCENARIO_ID)
                .orElseThrow();
        assertEquals("IMPACT_AVAILABLE", updatedScenario.getSummary().getWorkflowState(),
                "Workflow state should remain IMPACT_AVAILABLE after IMPACT_DATA_REFRESHED");
    }
}
